// Country Codes for phone numbers
export const COUNTRY_CODES = [
  { label: "+66 (Thailand)", value: "+66" },
  { label: "+1 (USA)", value: "+1" },
  { label: "+44 (UK)", value: "+44" },
  { label: "+81 (Japan)", value: "+81" },
  { label: "+86 (China)", value: "+86" },
  { label: "+91 (India)", value: "+91" },
  { label: "+61 (Australia)", value: "+61" },
  { label: "+49 (Germany)", value: "+49" },
  { label: "+33 (France)", value: "+33" },
  { label: "+39 (Italy)", value: "+39" },
  { label: "+34 (Spain)", value: "+34" },
  { label: "+82 (South Korea)", value: "+82" },
  { label: "+7 (Russia)", value: "+7" },
  { label: "+55 (Brazil)", value: "+55" },
  { label: "+52 (Mexico)", value: "+52" },
  { label: "+65 (Singapore)", value: "+65" },
  { label: "+64 (New Zealand)", value: "+64" },
  { label: "+31 (Netherlands)", value: "+31" },
  { label: "+46 (Sweden)", value: "+46" },
  { label: "+47 (Norway)", value: "+47" },
  { label: "+41 (Switzerland)", value: "+41" },
  { label: "+43 (Austria)", value: "+43" },
  { label: "+32 (Belgium)", value: "+32" },
  { label: "+45 (Denmark)", value: "+45" },
  { label: "+358 (Finland)", value: "+358" },
  { label: "+30 (Greece)", value: "+30" },
  { label: "+353 (Ireland)", value: "+353" },
  { label: "+351 (Portugal)", value: "+351" },
  { label: "+48 (Poland)", value: "+48" },
  { label: "+420 (Czech Republic)", value: "+420" },
  { label: "+36 (Hungary)", value: "+36" },
  { label: "+380 (Ukraine)", value: "+380" },
  { label: "+40 (Romania)", value: "+40" },
  { label: "+359 (Bulgaria)", value: "+359" },
  { label: "+385 (Croatia)", value: "+385" },
  { label: "+381 (Serbia)", value: "+381" },
  { label: "+421 (Slovakia)", value: "+421" },
  { label: "+386 (Slovenia)", value: "+386" },
  { label: "+354 (Iceland)", value: "+354" },
  { label: "+356 (Malta)", value: "+356" },
  { label: "+357 (Cyprus)", value: "+357" },
  { label: "+372 (Estonia)", value: "+372" },
  { label: "+371 (Latvia)", value: "+371" },
  { label: "+370 (Lithuania)", value: "+370" },
  { label: "+352 (Luxembourg)", value: "+352" },
  { label: "+853 (Macau)", value: "+853" },
  { label: "+63 (Philippines)", value: "+63" },
  { label: "+62 (Indonesia)", value: "+62" },
  { label: "+84 (Vietnam)", value: "+84" },
  { label: "+60 (Malaysia)", value: "+60" }
];

export const COUNTRIES = [
  { code: "TH", name: "Thailand" },
  { code: "US", name: "United States" },
  { code: "UK", name: "United Kingdom" },
  { code: "JP", name: "Japan" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "KR", name: "South Korea" },
  { code: "RU", name: "Russia" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "SG", name: "Singapore" },
  { code: "NZ", name: "New Zealand" },
  { code: "NL", name: "Netherlands" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "CA", name: "Canada" },
  { code: "CH", name: "Switzerland" },
  { code: "IE", name: "Ireland" },
  { code: "PH", name: "Philippines" },
  { code: "MY", name: "Malaysia" },
  { code: "ID", name: "Indonesia" },
  { code: "VN", name: "Vietnam" },
  { code: "HK", name: "Hong Kong" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" }
];

// Days for date of birth
export const DAYS = Array.from({ length: 31 }, (_, i) => i + 1);

// Months for date of birth
export const MONTHS = [
  { label: "Jan", value: "1" },
  { label: "Feb", value: "2" },
  { label: "Mar", value: "3" },
  { label: "Apr", value: "4" },
  { label: "May", value: "5" },
  { label: "Jun", value: "6" },
  { label: "Jul", value: "7" },
  { label: "Aug", value: "8" },
  { label: "Sep", value: "9" },
  { label: "Oct", value: "10" },
  { label: "Nov", value: "11" },
  { label: "Dec", value: "12" },
];

// Years for date of birth
const CURRENT_YEAR = new Date().getFullYear();
export const YEARS = Array.from(
  { length: CURRENT_YEAR - 1960 + 1 },
  (_, i) => 1960 + i
);

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "th", name: "Thai" },
  { code: "zh", name: "Chinese (Mandarin)" },
  { code: "es", name: "Spanish" },
  { code: "hi", name: "Hindi" },
  { code: "ar", name: "Arabic" },
  { code: "bn", name: "Bengali" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "ja", name: "Japanese" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "ko", name: "Korean" },
  { code: "tr", name: "Turkish" },
  { code: "it", name: "Italian" },
  { code: "vi", name: "Vietnamese" },
  { code: "pl", name: "Polish" },
  { code: "jv", name: "Javanese" },
  { code: "id", name: "Indonesian" },
  { code: "ms", name: "Malay" },
  { code: "fa", name: "Persian" },
  { code: "ur", name: "Urdu" },
  { code: "nl", name: "Dutch" },
  { code: "el", name: "Greek" },
  { code: "sv", name: "Swedish" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "he", name: "Hebrew" },
  { code: "cs", name: "Czech" },
  { code: "ro", name: "Romanian" },
  { code: "hu", name: "Hungarian" },
  { code: "uk", name: "Ukrainian" },
  { code: "no", name: "Norwegian" },
  { code: "sk", name: "Slovak" },
  { code: "hr", name: "Croatian" },
  { code: "sr", name: "Serbian" },
  { code: "bg", name: "Bulgarian" },
  { code: "lt", name: "Lithuanian" },
  { code: "lv", name: "Latvian" },
  { code: "et", name: "Estonian" }
];